### ISSUE TITLE
JLM spirte shows text backwards when facing left

### ISSUE THREAD

**Issue by M4xi1m3** [Insoumis/laec-est-toi#18]
**Describe the bug**
The text on the JLM sprite is flipped when the sprite is facing left

**To Reproduce**
1. Open a 

**Expected behavior**
The text should not be flipped

**Screenshots**
![image](https://user-images.githubusercontent.com/57234558/160305974-53c0a0f2-a0df-44d9-9228-710d06f01d21.png)

**Desktop (please complete the following information):**
 - OS: Linux x64
 - Version: 0.6.3

**Additional context**
This might happen on other controllable sprites with text (I don't know if there are any except the JLM turtle). A possible fix would be to add a second sprite used when facing left.

**Comment by domi41** [comment]
Thanks !   If anyone wants to tackle this on, the sprites are in `sprites/items/`.

**Comment by domi41** [comment]
This is fixed, now.  Slowly, but steadily.
